@access-token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyTmFtZSI6IlJ1dHVyYWogR2Fpa3dhZCIsImlhdCI6MTYzNDExNDY4NCwiZXhwIjoxNjM0MTE4Mjg0LCJpc3MiOiJNZU15c2VsZiJ9.0T8lyA8fLPtmPY_WwB0qkDxdAHSyM2CAxROYzQkMsF0

###
GET http://localhost:1998/blog
Authorization: Bearer {{access-token}}

###
GET http://localhost:1998/blog/6
Authorization: Bearer {{access-token}}

###
POST http://localhost:1998/user/login
Content-Type: application/json

{
    "email": "player@csk.com",
    "password": "whistlepodu"
}

###
PUT http://localhost:1998/blog/6
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
    "name": "Sameer",
    "content": "Keep yourself enlightened within."
}

###
DELETE http://localhost:1998/blog/5
Authorization: Bearer {{access-token}}